/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct intMatrix {
	struct {
		u_int numArray_len;
		int *numArray_val;
	} numArray;
};
typedef struct intMatrix intMatrix;

struct floatMatrix {
	struct {
		u_int muledArray_len;
		float *muledArray_val;
	} muledArray;
};
typedef struct floatMatrix floatMatrix;

struct mulFloat {
	struct {
		u_int numArray_len;
		int *numArray_val;
	} numArray;
	float multiplier;
};
typedef struct mulFloat mulFloat;

#define RPC_PROG 0x23451111
#define RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define findAverage 1
extern  float * findaverage_1(intMatrix *, CLIENT *);
extern  float * findaverage_1_svc(intMatrix *, struct svc_req *);
#define findMinMax 1
extern  intMatrix * findminmax_1(intMatrix *, CLIENT *);
extern  intMatrix * findminmax_1_svc(intMatrix *, struct svc_req *);
#define mulMatrixWithFloat 1
extern  floatMatrix * mulmatrixwithfloat_1(mulFloat *, CLIENT *);
extern  floatMatrix * mulmatrixwithfloat_1_svc(mulFloat *, struct svc_req *);
extern int rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define findAverage 1
extern  float * findaverage_1();
extern  float * findaverage_1_svc();
#define findMinMax 1
extern  intMatrix * findminmax_1();
extern  intMatrix * findminmax_1_svc();
#define mulMatrixWithFloat 1
extern  floatMatrix * mulmatrixwithfloat_1();
extern  floatMatrix * mulmatrixwithfloat_1_svc();
extern int rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intMatrix (XDR *, intMatrix*);
extern  bool_t xdr_floatMatrix (XDR *, floatMatrix*);
extern  bool_t xdr_mulFloat (XDR *, mulFloat*);

#else /* K&R C */
extern bool_t xdr_intMatrix ();
extern bool_t xdr_floatMatrix ();
extern bool_t xdr_mulFloat ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
