/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RPC.h"


void
rpc_prog_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	intMatrix  findaverage_1_arg;
	intMatrix  *result_2;
	intMatrix  findminmax_1_arg;
	floatMatrix  *result_3;
	mulFloat  mulmatrixwithfloat_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_PROG, RPC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = findaverage_1(&findaverage_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = findminmax_1(&findminmax_1_arg, clnt);
	if (result_2 == (intMatrix *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = mulmatrixwithfloat_1(&mulmatrixwithfloat_1_arg, clnt);
	if (result_3 == (floatMatrix *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rpc_prog_1 (host);
exit (0);
}
