/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "RPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

float *
findaverage_1(intMatrix *argp, CLIENT *clnt)
{
	static float clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, findAverage,
		(xdrproc_t) xdr_intMatrix, (caddr_t) argp,
		(xdrproc_t) xdr_float, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

intMatrix *
findminmax_1(intMatrix *argp, CLIENT *clnt)
{
	static intMatrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, findMinMax,
		(xdrproc_t) xdr_intMatrix, (caddr_t) argp,
		(xdrproc_t) xdr_intMatrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

floatMatrix *
mulmatrixwithfloat_1(mulFloat *argp, CLIENT *clnt)
{
	static floatMatrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, mulMatrixWithFloat,
		(xdrproc_t) xdr_mulFloat, (caddr_t) argp,
		(xdrproc_t) xdr_floatMatrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
